project:
  type: website
  output-dir: .

website:
  title: "Nayla Sol Garcilazo"
  favicon: favicon.png
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: about.qmd
        text: About me
      - href: codigo.qmd
        text: Computational Social Science
      - href: docencia.qmd
        text: Faculty
      - href: encuestas.qmd
        text: Surveys


    right:
      - text: "ES 🌐"
        href: "https://naylasolg.github.io/Site_Es/"
        target: _blank
      - text: "Contacto"
        menu: 
          - text: "Email"
            href: mailto:ngarcilazo@unsam.edu.ar
          - text: "LinkedIn"
            href: https://www.linkedin.com/in/nayla-sol-garcilazo/
            target: _blank



format:
  html:
    theme: minty